version: '3.8'

services:
  whats-for-dinner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whats-for-dinner
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
